name: neural_acd
version: v1.0

general:
  cut_point_threshold: 0.7

model:
  batch_size: 3
  learning_rate: 1e-3
  max_steps: 2000
  num_workers: 8

generation:
  min_parts: 3
  max_parts: 6
  random_rotation: false
  random_scale: false
  gaussian_filter: false
  normalize_mesh: true

lib:
  generation:
    cuboid:
      width_min: 0.1
      width_max: 0.5
    sphere:
      radius_min: 0.1
      radius_max: 0.25
      subdivs: 3

  pcd_res: 3000
  remesh:
    resolution: 50
    threshold: 0.01

  cost_rv_k: 0.03
  merge_threshold: 0.05

  jlinkage:
    sigma: 0.2
    num_samples: 10000
    threshold: 0.05
    outlier_threshold: 10
